### ISSUE TITLE
Alert: Installation Failed     Unable to sign you in to your Apple ID. Try again later. (-36607)

### ISSUE THREAD

**Issue by SoftwareRat** [powenn/AltServer-Linux-PyScript#1]

**Comment by SoftwareRat** [comment]
https://github.com/powenn/AltServer-Linux-ShellScript/issues/28

**Comment by bsdcpp** [comment]
Yes, I've also got this problem, and then my appleID been locked everytime you tried to install altstore.

**Comment by powenn** [comment]
Project rewtitten
