### ISSUE TITLE
Cannot get wifi sync to work on opensuse tumbleweed

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [powenn/AltServer-Linux-PyScript#11]
#####################################
#  Welcome to the AltServer script  #
#####################################

ScriptUsage: [OPTION]

OPTIONS
    i, --Install AltStore or ipa files
        Install AltStore or ipa files to your device
    w, --Switch to wifi Daemode mode (Default using it after launch)
        Switch and restart to wifi Daemode mode to refresh apps or AltStore
    t, --Switch to usb tethered Daemode mode
        Switch and restart to usb tethered Daemode mode to refresh apps or AltStore
    e, --Exit
        Exit script
    h, --Help
        Show this message
    p, --Pair
        Show paired devices
    u, --Update
        Update this script
        
For more information: 
https://github.com/powenn/AltServer-Linux-PyScript

Enter OPTION to continue : No argument supplied, if you want for help, please use -h or --help
Not supplying ipa, running in server mode!
Running python3 command to advertise AltServer: from ctypes import *; dll = CDLL('libdns_sd.so'); sdRef = c_int(); flags = 0; interfaceIndex = 0; name = None; regtype = br'_altserver._tcp'; domain = None; host = None; port = 62914; txtLen = 17; txtRecord = b'\x10\x73\x65\x72\x76\x65\x72\x49\x44\x3D\x31\x32\x33\x34\x35\x36\x37'; ret = dll.DNSServiceRegister(byref(sdRef), flags, interfaceIndex, name, regtype, domain, host, port, txtLen, txtRecord, None, None); print('DNSServiceRegister result: %d' % ret); from threading import Event; Event().wait(); 
Starting netmuxd
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
Listening on /var/run/usbmuxd
*** WARNING *** The program 'python3.11' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
DNSServiceRegister result: 0

This is what I see when running script but it does not detect my iphone. Note that when switching to usb tethered mode it does work.

**Comment by powenn** [comment]
All depends installed and services running ?

**Comment by TheAnnoyingFruit** [comment]
I ran the systemctl status commands and see that avahi-daemon.service and avahi-daemon.socket are both running. As for the dependencies I installed (libusbmuxd-2_0-6, libimobiledevice-1_0-6 libimobiledevice-glue-1_0-0, libavahi-client3 libavahi-common3 libavahi-core7 libavahi glib1, libdns_sd). All of these seem close to the listed debian dependencies, I could not find anything that was called libimobiledevice-utils though.

**Comment by powenn** [comment]
Check netmuxd,run as sudo,what's the output in console

**Comment by powenn** [comment]
iPhone and device connected to same WiFi ?

**Comment by powenn** [comment]
Also what's your opensuse version

**Comment by TheAnnoyingFruit** [comment]
My pc is connected via ethernet and my iphone is connected to the same network as the ethernet over wifi. Opensuse tumbleweed is a rolling release so there isn't a version number per se.

**Comment by TheAnnoyingFruit** [comment]
Also running netmuxd as sudo I get :
Starting netmuxd
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
Listening on /var/run/usbmuxd

**Comment by powenn** [comment]
> My pc is connected via ethernet and my iphone is connected to the same network as the ethernet over wifi. Opensuse tumbleweed is a rolling release so there isn't a version number per se.

That's the prob, they have to connect to the same WiFi network

**Comment by powenn** [comment]
You might need a WiFi adapter

**Comment by TheAnnoyingFruit** [comment]
Tested it on my laptop and it works, you are correct thank you for your prompt help.

**Comment by theoware** [comment]
Can you please add this to the readme? I had the same issue with my PC over ethernet and the device over WiFi
