### ISSUE TITLE
Can't install AltStore.ipa

### ISSUE THREAD

**Issue by ha1fdan** [powenn/AltServer-Linux-PyScript#15]
Enter OPTION to continue : p
iPhone SE 2 , 00008030-000XXXXXXXXX
Enter OPTION to continue : i
[0] : iPhone SE 2 , 00008030-000XXXXXXXXX
Enter the index of the device for installation : 0
Enter your Apple ID : xxxxxxxxxxxxxx@icloud.com
Enter password of the Apple ID :
Do you want to install AltStore ? (y/n) [n for select your own iPA] : y
Installing app...
parse anisette data ret
Alert: Could not install AltStore.ipa to unknown.
    Failed to connect to any resolved endpoint
Press any key to continue...

Exception: Failed to connect to any resolved endpoint
 0# 0x00000000005CF298
 1# 0x000000000099EC2C

Finished!

**Comment by powenn** [comment]
Needs more details like which option you using, T or W ?
And your installation procedure , for example , run the sciprt -> switch to T option -> plug in device

**Comment by RushGho** [comment]
I'm still having this issue and I've followed your installation procedure.
