### ISSUE TITLE
Can you please create a version without sudo?

### ISSUE THREAD

**Issue by esme518** [powenn/AltServer-Linux-PyScript#17]
Hi,

I am running this script inside docker.
For now, I can not run this as a daemon, because I need to enter sudo password(even if the user is root).
Can you please create a version without sudo or skip enter sudo password for root user.

Thanks.

**Comment by powenn** [comment]
https://github.com/powenn/AltServer-Linux-PyScript/issues/10#issuecomment-1643054078
