### ISSUE TITLE
Failed to connect to any resolved endpoint

### ISSUE THREAD

**Issue by Nosskirneh** [powenn/AltServer-Linux-PyScript#19]
Connected my device with USB and trust the connection on the device. It can then be paired with `idevicepair pair`.

Running the script from this repo starts things and these two lines are written every second or so:
```
Removing <udid>
Adding device <udid>
```

Then when trying to renew an app:
```
Other Socket:6. Port: 60693. Error: 0
Receiving request size...
Checking socket: 6
Received bytes: 4(of 4)
Receiving 48 bytes...
Checking socket: 6
Received bytes: 48(of 48)
parse anisette data ret
Represented Value: 241
Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
Failed to handle request:Failed to connect to any resolved endpoint
Sent Bytes Count: 241 (241)
Sent Data: 241 Bytes
```

Any idea what might be wrong?

**Comment by powenn** [comment]
Switch to t option before plugging in your device

**Comment by PallasDDLer** [comment]
I have tried this but I still get the error

**Comment by powenn** [comment]
which linux distro and what's its arch , did it running on VM or not ?

**Comment by PallasDDLer** [comment]
I am using antix (debian based with no systemd) not in a vm. 86x64

**Comment by not-yuvi** [comment]
i have the same issue

**Comment by not-yuvi** [comment]
using ubuntu 86x64

**Comment by powenn** [comment]
Is there any error logs in AltStore?

**Comment by PallasDDLer** [comment]
Yes, when I try to install an app it say "Failed to connect to any resolved endpoint"

**Comment by powenn** [comment]
That's a notification,what's the error logs

**Comment by PallasDDLer** [comment]
It is a notification but it also appears in the menu labeled "error log" with the code AltServer.ServerError 2000. I dont know a more detailed log.

**Comment by powenn** [comment]
AltStore > settings > error log > view more details

**Comment by Nosskirneh** [comment]
> AltStore > settings > error log > view more details

```
Error Description
Failed to connect to any resolved endpoint

Failure Reason
Failed to connect to any resolved endpoint

Title
Failed to Refresh <app name>
```

**Comment by powenn** [comment]
Tried tethered mode on my laptop and its worked 

What's your details os info 
For example,Debian 12 or Ubuntu 22.04 x64

Can be check by 'cat /etc/os-release' or others methods 

Also make sure dependencies are installed 

If still not working, have to check the executable binaries separately,one or some of them might not working properly

Pretty sure the script itself has no problems

**Comment by PallasDDLer** [comment]
`PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

**Comment by PallasDDLer** [comment]
I should say that I installed altstore a few days ago using windows 10, not in a vm.

**Comment by PallasDDLer** [comment]
I just uninstalled AltStore ,tried to install it using NyaMisty's deb program which I build, but the altstore that installed was outdated and gave an error about some provision and team so I couldnt update it. I uninstalled that again, saw that this python script was updated than I updated it but when I tried to install altstore it gave the error "failed to connect to any resolved endpoint". Afterwards I closed and reopened the script, it made some files like version.json and the resources folder with its content, tried again and some other variation of steps but same error.

**Comment by powenn** [comment]
This update just improve the updating process(written in release note)

Can you try on different machines or probably VMs or others Linux environments?

**Comment by powenn** [comment]
> I just uninstalled AltStore ,tried to install it using NyaMisty's deb program which I build, but the altstore that installed was outdated and gave an error about some provision and team so I couldnt update it. I uninstalled that again, saw that this python script was updated than I updated it but when I tried to install altstore it gave the error "failed to connect to any resolved endpoint". Afterwards I closed and reopened the script, it made some files like version.json and the resources folder with its content, tried again and some other variation of steps but same error.


Found this in close issue 

https://github.com/powenn/AltServer-Linux-PyScript/issues/6#issuecomment-1627576476

Check anisette-server , you might have to compile it manually

**Comment by PallasDDLer** [comment]
I used a lubuntu vm and it worked. I wanted to provide information in case this was a bigger issue but it might be that my linux is just too picky.

**Comment by powenn** [comment]
@Nosskirneh 
@yuvi-develop 

Check https://github.com/powenn/AltServer-Linux-PyScript/issues/19#issuecomment-1698601681
