### ISSUE TITLE
how do you install on manjaro

### ISSUE THREAD

**Issue by possyeater** [powenn/AltServer-Linux-PyScript#2]
i did everything correctly but in the end i get this /bin/sh: line 1: ./AltServer: No such file or directory

**Comment by possyeater** [comment]
i have fixed it

**Comment by powenn** [comment]
Not recommend using it,it is outdated,shell script is more convenient and better compatible

**Comment by possyeater** [comment]
How do you do that? It won't work on manjaro or am i doing something wrong?

**Comment by powenn** [comment]
Probably missing python modules,and just don't using it,it's for tested and outdated
