### ISSUE TITLE
Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.

### ISSUE THREAD

**Issue by BleakFox** [powenn/AltServer-Linux-PyScript#20]
Hi, when I try to install or refresh my ipa file and altstore, this message error appears:

`Failed to handle request:Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.
`
I have the same error in the shell version, but I fixed it by using the py version.. Can anyone help me?

**Comment by powenn** [comment]
Did you read the  README ?
Use Py edition instead ,the  shell one no longer maintain

**Comment by BleakFox** [comment]
as I texted, I did it few moth ago, and this solution worked. Now also the python version has the same error.

**Comment by BleakFox** [comment]
I saw the issue is been reopened, anything changed in the py version? any update or fix? thanks in advance

**Comment by powenn** [comment]
This was caused by anisette server not working properly, check does this binary works on your device by executing it manually , also try removing this binary and re run the script to let the script re download the binary

**Comment by powenn** [comment]
Also this should not occurred,since py edition was designed for solving the issue by adding anisette server supports

**Comment by BleakFox** [comment]
excuse my ignorance, what do u mean to check "this binary" and how could I remove the "binary" from the script?

**Comment by powenn** [comment]
There is a resource dir on the same path where your script place, try executing it and checking its output

**Comment by BleakFox** [comment]
okay i did, in the diredtory there is 3 files. 
if I execute the file: AltServer, i get this output:
```
No argument supplied, if you want for help, please use -h or --help
Not supplying ipa, running in server mode!
Running python3 command to advertise AltServer: from ctypes import *; dll = CDLL('libdns_sd.so'); sdRef = c_int(); flags = 0; interfaceIndex = 0; name = None; regtype = br'_altserver._tcp'; domain = None; host = None; port = 12241; txtLen = 17; txtRecord = b'\x10\x73\x65\x72\x76\x65\x72\x49\x44\x3D\x31\x32\x33\x34\x35\x36\x37'; ret = dll.DNSServiceRegister(byref(sdRef), flags, interfaceIndex, name, regtype, domain, host, port, txtLen, txtRecord, None, None); print('DNSServiceRegister result: %d' % ret); from threading import Event; Event().wait(); 
*** WARNING *** The program 'python3.10' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
DNSServiceRegister result: 0
```

there is anisette-server that give me in output:
```
 app INFO  2023-09-10T22:38:15.816 anisette-server-provision v2.2.0
                     app INFO  2023-09-10T22:38:15.867 Ready! Serving data.
```
finally, the last executable file is the netmuxd file that give me in output: 
```
Starting netmuxd
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/main.rs:144:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BleakFox** [comment]
![image](https://github.com/powenn/AltServer-Linux-PyScript/assets/60853053/78ce3a91-2abf-41b6-a50a-07d54e046513)

how u can see, there is also a Altsore.ipa file, not executable by terminal, i think it's just the .ipa file that the script install on the device when I install Altstore

**Comment by BleakFox** [comment]
okay, thanks @powenn I solved. I completely deleted the py script and re installed it, and this worked. Thanks for the help
