### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by butckhe** [powenn/AltServer-Linux-PyScript#21]
Hi, i installed all dependecies, but i cannot run the script.

`Traceback (most recent call last):
  File "main.py", line 363, in <module>
    class DeviceManager:
  File "main.py", line 367, in DeviceManager
    def getDevices(self) -> list[iDevice]:
TypeError: 'type' object is not subscriptable`

**Comment by powenn** [comment]
Python version ?
Host architecture ?

**Comment by t0bse** [comment]
same here, raspberry pi 3 and python 3.7.0

**Comment by powenn** [comment]
os version ?

can get with `cat /etc/os-release`

**Comment by t0bse** [comment]
> cat /etc/os-release

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by powenn** [comment]
Try upgrade python

**Comment by powenn** [comment]
https://stackoverflow.com/questions/64496437/python-list-type-declaration
