### ISSUE TITLE
The script can't handle the ampersand character  "&" in the Apple ID password

### ISSUE THREAD

**Issue by moritz-john** [powenn/AltServer-Linux-PyScript#26]
This took me way too long too figure out so I make it brief:

Let's say for example your Apple ID Password is: `a23&s&b443d`
This will brake the script:
```python
[...]
Enter your Apple ID : example@appleid.com
Enter password of the Apple ID : 
Do you want to install AltStore ? (y/n) [n for select your own iPA] : y
/bin/sh: 1: b443d: not found
/bin/sh: 1: s: not found
[...]
```
---
`/bin/sh: 1: b443d: not found` matches the `&b443d` part of the password, while `/bin/sh: 1: s: not found` matches `&s`

The script does not seem to handle the ampersand character  "&" (and I am not sure about other special characters).

**Comment by powenn** [comment]
I will looking for solutions

**Comment by powenn** [comment]
Try update the script , I have publish new release

**Comment by moritz-john** [comment]
> Try update the script , I have publish new release

Thank you very much for your work, it's fixed and does work now! :)
