### ISSUE TITLE
Packages already newest version, nothing happens

### ISSUE THREAD

**Issue by ap46281** [powenn/AltServer-Linux-PyScript#3]
Trying to use python route to install but every time I run the two commands it tells me 254 not upgraded and nothing new seems to appear to continue to next step.

root@debian:~# sudo apt-get install usbmuxd libimobiledevice6 libimobiledevice-utils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libimobiledevice-utils is already the newest version (1.2.1~git20181030.92c5462-2+deb10u1).
libimobiledevice6 is already the newest version (1.2.1~git20181030.92c5462-2+deb10u1).
usbmuxd is already the newest version (1.1.1~git20181007.f838cf6-1).
0 upgraded, 0 newly installed, 0 to remove and 254 not upgraded.
root@debian:~# sudo apt-get install wget curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u2).
wget is already the newest version (1.20.1-1.1).
0 upgraded, 0 newly installed, 0 to remove and 254 not upgraded.

**Comment by powenn** [comment]
Python edition outdated,use shell script instead,and to solve not upgraded problems just do sudo apt upgrade

**Comment by powenn** [comment]
Project rewtitten
