### ISSUE TITLE
KeyError: 'tag_name'

### ISSUE THREAD

**Issue by mr00k3** [powenn/AltServer-Linux-PyScript#43]
![Screenshot from 2024-03-12 07-05-15](https://github.com/powenn/AltServer-Linux-PyScript/assets/36767322/25530a65-989c-4180-a013-0664d0cb9c81)

**Comment by powenn** [comment]
Try run the script again,I just did some tests and everything worked fine ,this issue shouldn't occur

**Comment by mr00k3** [comment]
after two reboots script works
