### ISSUE TITLE
Not able to Wifi refresh on altserver raspberry pi 4

### ISSUE THREAD

**Issue by TheRealKushal** [powenn/AltServer-Linux-PyScript#9]
I can properly use tethered mode in order to install altstore and refresh it but the wifi refresh does not work even though both the avahi daemon and socket are both running and active. The computer is trusted by the iPhone but when I refresh with altserver it says "altserver could not find this device" and on my linux machine it says "Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
Sent Bytes Count: 86 (86)
Sent Data: 86 Bytes
Failed to handle request:AltServer could not find the device."

**Comment by powenn** [comment]
Does WiFi installation works?

**Comment by TheRealKushal** [comment]
I have not tried that because I installed altstore with usb connected

**Comment by powenn** [comment]
Give a try,just install again don't need uninstall it before

**Comment by TheRealKushal** [comment]
do I install altstore or any app with wifi

**Comment by powenn** [comment]
I have tested aarch64 with VM,and everything works 🤔

**Comment by powenn** [comment]
AltStore for faster testing

**Comment by powenn** [comment]
In fact press enter when asking yes or no you get it installing

**Comment by TheRealKushal** [comment]
the wifi installation of altstore is not working because it says altserver could not find this device

**Comment by powenn** [comment]
I think @Macleykun might know how to solve it,he also uses raspberry pi

**Comment by powenn** [comment]
@TheRealKushal can you exec netmuxd ? 

Try sudo netmuxd and check its output

**Comment by Macleykun** [comment]
Check: `systemctl status avahi-daemon.s` are they both enabled and running?
if not, use systemctl enable --now (nameoftheservice) to do so.
If you somehow missing these two, you can install the package then: avahi-daemon

like powenn said, you also need to have altserver running with netmuxd turned on.

#shamelssplug
Altstore requires you to use altserver and be connected to the same network over wifi. But if you use SideStore you only need to install it, and if your connected to a network (wifi) and have the vpn on (don't worry, it's one that goes back to your device). Then it will also refresh.
Start with Sidestore by reading here: https://wiki.sidestore.io/guides/install.html

**Comment by TheRealKushal** [comment]
pi@kushal:~ $ sudo netmuxd 
sudo: netmuxd: command not found
pi@kushal:~ $ systemctl status avahi-daemon.s
Unit avahi-daemon.s.service could not be found.
pi@kushal:~ $ 

pi@kushal:~ $ systemctl status avahi-daemon
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor >
     Active: active (running) since Sun 2023-07-09 08:45:55 MST; 23h ago
TriggeredBy: ● avahi-daemon.socket
   Main PID: 202844 (avahi-daemon)
     Status: "avahi-daemon 0.8 starting up."
      Tasks: 2 (limit: 3932)
        CPU: 19.324s
     CGroup: /system.slice/avahi-daemon.service
             ├─202844 avahi-daemon: running [kushal.local]
             └─202846 avahi-daemon: chroot helper

Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for>
Jul 09 08:45:56 kushal avahi-daemon[202844]: Server startup complete. Host name>
lines 1-22/22 (END)


and also do I need a pc for the installing sidestore for the first time

**Comment by Macleykun** [comment]
> pi@kushal:~ $ sudo netmuxd sudo: netmuxd: command not found pi@kushal:~ $ systemctl status avahi-daemon.s Unit avahi-daemon.s.service could not be found. pi@kushal:~ $
> 
> pi@kushal:~ $ systemctl status avahi-daemon ● avahi-daemon.service - Avahi mDNS/DNS-SD Stack Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor > Active: active (running) since Sun 2023-07-09 08:45:55 MST; 23h ago TriggeredBy: ● avahi-daemon.socket Main PID: 202844 (avahi-daemon) Status: "avahi-daemon 0.8 starting up." Tasks: 2 (limit: 3932) CPU: 19.324s CGroup: /system.slice/avahi-daemon.service ├─202844 avahi-daemon: running [kushal.local] └─202846 avahi-daemon: chroot helper
> 
> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:55 kushal avahi-daemon[202844]: Registering new address record for> Jul 09 08:45:56 kushal avahi-daemon[202844]: Server startup complete. Host name> lines 1-22/22 (END)
> 
> and also do I need a pc for the installing sidestore for the first time

netmuxd is a binairy that's i believe in resource, there you can start it, then try to wifi refresh.

No, ya are setting up AltServer to install altstore, but you can also specify your own IPA which is sidestore in this case. But if you find it easier to use AltServer on windowsto install Sidestore that's ok too (believe SideStore server is comming out/is out)

**Comment by TheRealKushal** [comment]
netmuxd doesn't seem to be working but soon I will try sidestore cuz i can't try it now due to all of my 10 app ids being used thanks for the help.

**Comment by powenn** [comment]
> netmuxd doesn't seem to be working but soon I will try sidestore cuz i can't try it now due to all of my 10 app ids being used thanks for the help.

What if we use qemu to exec netmuxd, me and @Macleykun got x86 jitterbug works on arm with qemu

**Comment by Macleykun** [comment]
https://github.com/jkcoxson/netmuxd/releases/tag/v0.1.4
netmuxd already is on aarch64/armv7 and x86_64. only not 32-bit but i assume nobody really uses that.

**Comment by ak4153** [comment]
Interesting.
executing sudo ./resource/netmuxd adds the device.
And running python main.py handles the requests and signs the apps.

What I did prior:
1. Plug in my ipad in my orangepi and trusting it.
2.executing sudo ./resource/netmuxd adds the device.
3. running main.py and it works
